module.exports = {
    theme: {
        extend: {
            maxHeight: {
                '112': '28rem',
            },
        },
        colors: {
            transparent: 'transparent',
            primary: '#202020',
            secondary: '#707070',
            te: '#383838',
            sd: '#b3b3b3',
            footer: '#525252',
            main: '#141414',
            devil: '#666666',
            white: '#ffffff',
            black: '#000000',
        },
        spacing: {
            px: '1px',
            '0': '0',
            '1': '0.25rem',
            '2': '0.5rem',
            '3': '0.75rem',
            '4': '1rem',
            '5': '1.25rem',
            '6': '1.5rem',
            '8': '2rem',
            '10': '2.5rem',
            '12': '3rem',
            '14': '3.5rem',
            '16': '4rem',
            '20': '5rem',
            '24': '6rem',
            '32': '8rem',
            '40': '10rem',
            '48': '12rem',
            '56': '14rem',
            '64': '16rem',
            '72': '18rem',
            '80': '20rem',
            '88': '22rem',
            '112': '28rem',
        },
    },
    variants: {
        borderWidth: ['focus-within'],
        borderColor: ['responsive', 'hover', 'focus', 'focus-within'],
        backgroundColor: ['responsive', 'hover', 'focus', 'focus-within'],
        textColor: ['responsive', 'hover', 'focus', 'focus-within'],
        margin: ['responsive', 'first', 'last'],
    },
    plugins: [],
}
